### ISSUE TITLE
bug(build): fail to build with LLVM 20.1.8

### ISSUE THREAD

**Issue by shyeyian** [clice-io/clice#208]
```sh
/* copy 3 clang private headers... */
[anonymous@matebook build]$ uname -a
Linux matebook 6.16.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Aug 2025 15:32:49 +0000 x86_64 GNU/Linux
[anonymous@matebook clice]$ pwd
/opt/clice
[anonymous@matebook clice]$ ls
build  configure.sh  git
[anonymous@matebook clice]$ git -C git remote -v
origin  https://github.com/clice-project/clice (fetch)
origin  https://github.com/clice-project/clice (push)
[anonymous@matebook build]$ clang++ --version
clang version 20.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

[anonymous@matebook clice]$ cd build
[anonymous@matebook build]$ cmake -DCMAKE_INSTALL_PREFIX=.. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_INSTALL_PATH=/usr ../git
/* configure output... */
[anonymous@matebook build]$ cmake --build . -j20
/* build output... */
[ 32%] Building CXX object CMakeFiles/clice-core.dir/src/AST/Resolver.cpp.o
In file included from /opt/clice/git/src/AST/Resolver.cpp:1:
/opt/clice/git/include/AST/Resolver.h:44:16: error: no matching member function for call to 'lookup'
   44 |         return lookup(type->getQualifier(), type->getIdentifier());
      |                ^~~~~~
/opt/clice/git/include/AST/Resolver.h:41:19: note: candidate function not viable: no known conversion from 'NestedNameSpecifier' to 'const clang::NestedNameSpecifier *' for 1st argument
   41 |     lookup_result lookup(const clang::NestedNameSpecifier* NNS, clang::DeclarationName name);
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:75:19: note: candidate function not viable: requires single argument 'decl', but 2 arguments were provided
   75 |     lookup_result lookup(const clang::UnresolvedUsingValueDecl* decl) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:71:19: note: candidate function not viable: requires single argument 'expr', but 2 arguments were provided
   71 |     lookup_result lookup(clang::CXXDependentScopeMemberExpr* expr) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:66:19: note: candidate function not viable: requires single argument 'expr', but 2 arguments were provided
   66 |     lookup_result lookup(const clang::UnresolvedMemberExpr* expr) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:55:19: note: candidate function not viable: requires single argument 'expr', but 2 arguments were provided
   55 |     lookup_result lookup(const clang::UnresolvedLookupExpr* expr) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:51:19: note: candidate function not viable: requires single argument 'expr', but 2 arguments were provided
   51 |     lookup_result lookup(const clang::DependentScopeDeclRefExpr* expr) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:47:19: note: candidate function not viable: requires single argument 'type', but 2 arguments were provided
   47 |     lookup_result lookup(const clang::DependentTemplateSpecializationType* type) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:43:19: note: candidate function not viable: requires single argument 'type', but 2 arguments were provided
   43 |     lookup_result lookup(const clang::DependentNameType* type) {
      |                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/clice/git/include/AST/Resolver.h:48:29: error: no member named 'getQualifier' in 'clang::DependentTemplateSpecializationType'
   48 |         return lookup(type->getQualifier(), type->getIdentifier());
      |                       ~~~~  ^
/opt/clice/git/include/AST/Resolver.h:48:51: error: no member named 'getIdentifier' in 'clang::DependentTemplateSpecializationType'
   48 |         return lookup(type->getQualifier(), type->getIdentifier());
      |                                             ~~~~  ^
```

This error also occurs when `-DCMAKE_CXX_COMPILER=g++` (with g++ --version == 15.2).

**Comment by 16bit-ykiko** [comment]
clang breaks the API in new llvm version, we currently use llvm 20.1.5, see https://clice.io/zh/dev/build.html.
